### PR TITLE
adding stuff

### PR DESCRIPTION
**Pull request by pauly0594**

### CODE REVIEW

**Comment by bakercp** [comment]
A couple things:

1.  Please add a more descriptive title (and optionally a description) to the PR.  It's a good habit to get into if you get involved in the open source world.
2.  In order for the post to link to you and have meta data, etc you need to include a header.  You can basically copy / paste / modify the header from my [example](https://raw.githubusercontent.com/bakercp/InteractiveArt2015/gh-pages/_posts/2015-09-04-HelloWorld.md):

```
---
layout: post
title:  "Hello World"
date:   2015-09-01 00:00:00
categories: post
author: bakercp
---
```

3.  Idea 4 starts to get more specific, but ideas 1-3 need a bit more detail ... perhaps some sketches or examples from previous work to illustrate what you're talking about?

**Comment by bakercp** [comment]
Also, I'm excited to see what you come up with ... I'm kind of hoping someone will do something like this: http://cyrildiagne.com/interactive-projection-mapping to get the IO lab and projection working.

**Comment by pauly0594** [comment]
I wasn't descriptive because this is a new field for me not sure what i can
do before the due date and I never messed with projection mapping. I was
hoping you would point me in the right direction to which one to use that
is manageable

**Comment by bakercp** [comment]
Totally got it.  So, take a look at the link I posted above.  I'd say we should focus on some basic mapping principles and try to map some projections onto a small static object (not spinning).  We could focus on masking techniques (how to block out certain parts) and also some basic warping techniques, etc.  Gather up a few more examples of the kinds of things you'd like to do and then we can go into a bit more depth on how to make it into a manageable first project.

**Comment by pauly0594** [comment]
Will do once I am in an internet zone. A background of why I am super
intrested in projection mapping/interaction ...below. Basically I want to
do that for my masters/phd. I am totally sure its doable one day :). I
think projection mapping is a good start since the interaction that I speak
below will be similar to projection mapping. P.s.. Part of my fullbright
proposal...

 While being at the National Cheng Kung University, I would like to spend
my researching and developing a way to remove the heavily staring of
screens and move onto the world. By this I mean that it has become a
problem to always be staring at the screen, I find myself staring at screen
for everything. This has become a problem because the majority of our life
is heavily place on the web, and to access it we need to stare at a screen.
I would like to invent an interface on which the user would use it as an
extension of herself/himself. I have taken note that wearable might be the
answer to this problem; since clothes is one of the few items that can
fully integrate to our daily life style. Right now there are some attempts
to this technology with the Apple watch, Android watches, and Google Glass
but they still have not successfully integrated it with our lifestyles. My
answer to this dilemma is I would design wristbands that cover our hands
with an invisible field, which then allow the user to touch anything and
create an interactive surface. The invisible field would then wrap around
the object and become what ever we choose for it to become.

**Pull request merged**
